config/routes.rb
Rails.application.routes.draw do
  resources :phones do
    resources :messages, only: [:index, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :twilio, only: :create, controller: 'twilio'

  mount Resque::Server.new, :at => "/resque"

  root to: redirect('/phones')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone.rb
class Phone < ApplicationRecord

  has_many :text_messages

  validate :number_is_valid

  before_save :strip_number

  def create_message!(message:)
    self.text_messages.create!(
      message: message,
      inbound: false
    )
  end

private

  def number_is_valid
    unless valid_number?
      self.errors.add(:number, 'should have exactly 10 digits');
    end
  end

  def valid_number?
    self.number.present? &&
    self.number.match(/\A[\(\)\-\s0-9]+\Z/) &&
    self.number.gsub(/[^0-9]/, '').length == 10
  end

  def strip_number
    if self.number.present?
      self.number = self.number.gsub(/[^0-9]/, '')
    end
  end
end

app/models/text_message.rb
class TextMessage < ApplicationRecord

  after_commit :queue_send_to_twilio, on: :create
  belongs_to :phone

  def send!
    if sent_at.blank?
      client = Twilio::REST::Client.new(
        ENV['TWILIO_ACCOUNT_SID'],
        ENV['TWILIO_AUTH_TOKEN']
      )

      response = client.messages.create(
        from: ENV['TWILIO_PHONE_NUMBER'],
        to: "+1#{phone.number}",
        body: message
      )

      if response.error_code.blank?
        update!(sent_at: Time.now)
      end
    end

    true
  end

private

  def queue_send_to_twilio
    if !inbound?
      SendSmsToTwilioJob.perform_later(id)
    end
  end
end

app/models/twilio_request.rb
class TwilioRequest < ApplicationRecord

  after_commit :queue_process_job!, on: :create

  def process!
    if processed_at.blank?
      phone = Phone.find_by(number: raw_params['From'][-10 .. -1])

      if phone.present?
        TextMessage.create!(
          phone: phone,
          inbound: true,
          message: raw_params['Body']
        )

        self.update!(processed_at: Time.now)

        ActionCable.server.broadcast 'phone', update: true
      end
    end

    true
  end

  def queue_process_job!
    ProcessTwilioRequestJob.perform_later(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    phone = Phone.find(params[:phone_id])
    @text_messages = phone.text_messages.order(created_at: :desc).limit(10).reverse

    render json: {
      body: render_to_string(partial: 'index')
    }
  end

  def create
    @phone = Phone.find(params[:phone_id])
    @phone.create_message!(message: params[:text_message][:message])

    head 200
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = PhoneDecorator.decorate_collection(Phone.all)
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    @text_message = TextMessage.new
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id]).decorate
    end

    # Only allow a list of trusted parameters through.
    def phone_params
      params.require(:phone).permit(:name, :number)
    end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController

  skip_before_action :verify_authenticity_token
  before_action :verify_api_token

  def create
    TwilioRequest.create!(raw_params: params)

    head 200
  end

  def verify_api_token
    unless params[:twilio_api_token] == ENV['TWILIO_API_TOKEN']
      head 401
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ctm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'shared/javascript_onload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_index.html.erb
<% if @text_messages.present? %>
  <div class='text-messages'>
    <% @text_messages.each do |message| %>
      <%= tag.div class: (message.inbound? ? 'inbound' : 'outbound') do %>
        <%= tag.span message.message %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/phones/_form.html.erb
<%= form_with(model: phone, local: true) do |form| %>
  <% if phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
        <% phone.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.name %></td>
        <td><%= phone.number %></td>
        <td><%= link_to 'Show', phone %></td>
        <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
        <td><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone', new_phone_path %>

app/views/phones/new.html.erb
<h1>New Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @phone.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @phone.number %>
</p>

<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>

<hr>

<div id='messages'></div>

<%= form_for @text_message, url: phone_messages_path(@phone, @text_message), remote: true, authenticity_token: true, html: {class: 'form-inline'} do |f| %>
  <div class="input-group">
    <div class='input-wrapper'>
      <%= f.text_field :message, placeholder: "Text Message", class:  "form-control mb-2 mr-sm-2" %>
    </div>
    <div class="input-group-append">
      <%= f.submit 'Send', class: "btn btn-primary mb-2" %>
    </div>
  </div>
<% end %>

<% content_for :javascript_onload do %>
  Messages.init('<%= phone_messages_path(@phone.id) %>');
<% end %>

app/views/shared/_javascript_onload.html.erb
<% javascript_onload = yield(:javascript_onload) %>
<% unless javascript_onload.blank? %>
  <%= javascript_tag do %>
    document.addEventListener("DOMContentLoaded", function(){
      <%= javascript_onload.split('\n').join('\n  ').gsub("&quot;", "'").html_safe %>
    });
  <% end %>
<% end %>